services:

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub

    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-chrome

    shm_size: 2gb

    depends_on:
      - selenium-hub

    ports:
      - "7900:7900"

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1

  firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-firefox

    shm_size: 2gb

    depends_on:
      - selenium-hub

    ports:
      - "7901:7900"

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1

  tests:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: saucedemo-tests

    profiles:
      - tests

    depends_on:
      - selenium-hub
      - chrome
      - firefox

    environment:
      - SELENIUM_GRID_URL=http://selenium-hub:4444
      - SAUCE_BROWSER=chrome
      - SAUCE_HEADLESS=false